runtime: python27
api_version: 1
threadsafe: true
service: app
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- .*node_modules.*

handlers:
- url: /.*
  script: main.app
